// Extended list of disposable/temporary email domains
export const TEMP_EMAIL_DOMAINS = [
  'tempmail.com',
  'throwaway.email',
  'guerrillamail.com',
  'guerrillamail.org',
  '10minutemail.com',
  'mailinator.com',
  'temp-mail.org',
  'fakeinbox.com',
  'trashmail.com',
  'yopmail.com',
  'sharklasers.com',
  'getnada.com',
  'maildrop.cc',
  'dispostable.com',
  'tempail.com',
  'throwawaymail.com',
  'mohmal.com',
  'emailondeck.com',
  'tempr.email',
  'discard.email',
  'temporary-mail.net',
  'tmpmail.org',
  'tmpmail.net',
  'guerrillamail.biz',
  'guerrillamail.de',
  'guerrillamail.net',
  'spam4.me',
  'grr.la',
  'pokemail.net',
  'mailnesia.com',
  'mintemail.com',
  'temp-mail.io',
  'emailfake.com',
  'generator.email',
  'mailpick.biz',
  'disposableemailaddresses.com',
  'tempinbox.com',
  'mailcatch.com',
  'spamgourmet.com',
  'mytrashmail.com',
  'getairmail.com',
  'mailexpire.com',
  'tempsky.com',
  'inboxalias.com',
  'incognitomail.org',
  'dropmail.me',
  'instantemailaddress.com',
  'mailsac.com',
  'burnermail.io',
  'tempmailo.com'
];

export const isTemporaryEmail = (email: string): boolean => {
  const domain = email.toLowerCase().split('@')[1];
  return TEMP_EMAIL_DOMAINS.includes(domain);
};
